name: Java CI with Gradle

on:
  push:
    branches: [ "develop" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3

      - name: Set up JDK 16
        uses: actions/setup-java@v3
        with:
          java-version: '16'
          distribution: 'corretto'

      ## create application-dev.yml
      - name: make application-dev.yml
        run: |
          ## create application-dev.yml
          cd ./src/main/resources
          
          # sensitive.yaml 파일 생성
          touch ./application-dev.yml
          
          # GitHub-Actions 에서 설정한 값을 application-dev.yaml 파일에 쓰기
          echo "${{ secrets.SENSITIVE_KEY_VALUE }}" >> ./application-dev.yml
        shell: bash

      ## gradle build
      - name: Build with Gradle
        run: ./gradlew bootJar


      ## 웹 이미지 빌드 및 도커허브에 push
      - name: web docker build and push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_REPO }}/hometerview .
          docker push ${{ secrets.DOCKER_REPO }}/hometerview

      ## docker compose up
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ec2-user
          key: ${{ secrets.PEM_KEY }}
          script: |
            sudo docker ps
            sudo docker-compose down
            sudo docker rmi ${{ secrets.DOCKER_REPO }}/hometerview -f
            sudo docker image prune -f
            sudo docker-compose up -d
